### PR TITLE
Add stream client

### PR DESCRIPTION
**Pull request by maximpertsov**
Expose methods to add and remove a stream. We don't have a defined API streaming yet, but this feels like a good starting point for making it easy to setup streams.

JIRA: https://viam.atlassian.net/browse/RSDK-1019

### CODE REVIEW

**Review by edaniels — APPROVED** [review]
LGTM as a temp thing since ideally this would be performed by the camera stream API

**Comment by maximpertsov** [comment]
> LGTM as a temp thing since ideally this would be performed by the camera stream API

just to confirm, the camera proto does not have a stream api yet, right?

**Comment by maximpertsov** [comment]
> > LGTM as a temp thing since ideally this would be performed by the camera stream API
> 
> just to confirm, the camera proto does not have a stream api yet, right?

Yeah looks like we don't - I agree it should totally be part of that once we add it.

**Comment by edaniels** [comment]
It doesn't need a stream api proto to make a good client API. Camera API here in TS can call the stream methods for you. I don't think we will add those to the camera API anyway. That's for streaming frames, not starting a webrtc track

**Pull request merged**
